### ISSUE TITLE
Prepare next HypriotOS release "Blackbeard"

### ISSUE THREAD

**Issue by DieterReuter** [hypriot/image-builder-rpi#105]
This is the task list for the next HypriotOS release "Blackbeard" for all Raspberry Pi models. Docker is preparing a major release with Docker Engine 1.12 and is also updating all the other tools, so we'll update HypriotOS to use all the new Docker tools as soon as possible. All changes should be done in single pull requests in order to keep them small and independently.

- [x] prepare ReleaseNotes for HypriotOS 1.0.0-rc1, #126
- [x] update Linux kernel 4.4.15, https://github.com/hypriot/rpi-kernel/pull/25
  - [x] add Linux kernel 4.4.15 packages, #106
- [x] update docker-engine 1.12.1-rc1, #124
- [x] update docker-engine 1.12.1-rc2, #128 
- [x] update docker-engine 1.12.1, #130 
- [x] update docker-machine 0.8.0, https://github.com/hypriot/arm-machine/pull/4
  - [x] add docker-machine_0.8.0-30_armhf.deb, #111
- [x] update docker-compose 1.8.0, https://github.com/hypriot/arm-compose/pull/9
  - [x] add docker-compose_1.8.0-61_armhf.deb, #116
- [x] update device-init 0.1.8, https://github.com/hypriot/device-init/issues/23
  - [x] add docker-init_0.1.8_armhf.deb, #115
- [x] update roots 1.0.0-rc1, #121 
  - [x] switch back to `ID=raspbian` in `/etc/os-release`, https://github.com/hypriot/os-rootfs/pull/43
  - [x] clean APT cache and lists to reduce rootfs size, https://github.com/hypriot/os-rootfs/pull/45
    - this saves approx. 128 MByte in total
- [x] update rootfs 1.0.0, #129 
- [x] ensure compatibility with Docker install.sh, #117
  - [x] add lsb-release package, #118
- [x] clean APT cache and lists to reduce SD image size, #120
  - this saves approx. 220 MByte in total
- [x] update RPI raw image to v0.2.2, #122
  - [x] reduce RPI image size to 1000M, https://github.com/hypriot/image-builder-raw/pull/9
    - this reduces the time to flash the SD image down to 2mins
- [x] remove package libraspberrypi-doc_*_armhf.deb, #123
  - this saves approx. 30 MByte in total
- [x] don't install linux-headers to save disk space, #128
- [x] OPTIONAL: remove hypriot-cluster-lab, #125
  - [x] remove hypriot-cluster-lab package
  - [x] remove pre-installed consul image
  - [x] remove pre-installed swarm image
  - this saves approx. 10 MByte in total
- [x] NO/maybe later: switching to `overlay2` storage driver, for details read https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by Govinda-Fichtner** [comment]
@DieterReuter I wonder if it still makes sense to leave the Cluster Lab as part of the image as the Swarm Mode and Cluster Lab should work side by side. Cluster Lab uses the old but not deprecated way of using Swarm with Consul... 

If people still want to use it, it is still there. If not it is not in the way of using Docker Swarm mode.

What do you think?

**Comment by DieterReuter** [comment]
@Govinda-Fichtner We could leave it for now, and decide later whether we want to keep it or drop it. I'll change it to an optional task.

**Comment by DieterReuter** [comment]
Great to close long running issue. 😄
